export const CREATE_PRODUCT_BEGIN = "CREATE_PRODUCT_BEGIN";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";
export const UPLOAD_BEGIN = "UPLOAD_BEGIN";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_ERROR = "UPLOAD_ERROR";
export const HANDLE_CHANGE = "HANDLE_CHANGE";
